version: 2
jobs:
  build:
    working_directory: ~/circleci-kloudformation-generator
    docker:
    - image: circleci/openjdk:8-jdk-browsers
    steps:
    - checkout
    - run: cp pom.xml pomCopy.xml
    - restore_cache:
        keys:
        - maven-{{ checksum "pomCopy.xml" }}
    - run: mvn versions:set -DnewVersion=0.1.$CIRCLE_BUILD_NUM
    - run: MAVEN_OPTS="-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn" && mvn -s settings.xml -B deploy
    - store_artifacts:
        path: pom.xml
    - save_cache:
        paths:
        - ~/.m2
        key: maven-{{ checksum "pomCopy.xml" }}