version: 2
jobs:
  build:
    working_directory: ~/circleci-kloudformation-generator
    docker:
    - image: circleci/openjdk:8-jdk-browsers
    steps:
    - checkout
    - restore_cache:
        keys:
        - maven-{{ checksum "pom.xml" }}
    - run: mvn versions:set -DnewVersion=0.1.$CIRCLE_BUILD_NUM
    - run: mvn -s settings.xml -DskipTests=true source:jar deploy
    - store_artifacts:
        path: target/kloudformation-0.1.$CIRCLE_BUILD_NUM.jar
    - save_cache:
        paths:
        - ~/.maven
        key: maven-{{ checksum "pom.xml" }}